name: API Fetch Demo

on: [workflow_dispatch]   # Manually trigger the workflow

jobs:
  fetch-api-data:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Call GitHub API
      
        run: |
          # Fetch latest GitHub Actions runner release info
          response=$(curl -s https://api.github.com/repos/actions/runner/releases/latest)
          echo "Full API Response:"
          echo "$response"
          
        
          
          
