name: Terraform Release Fetch

on: [workflow_dispatch]

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      tf_version: ${{ steps.getversion.outputs.version }}
    steps:
      - name: Step 1 - Fetch Terraform latest version
        id: getversion
        run: |
          response=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest)
          echo "Full API Response: $response"
          version=$(echo "$response" | jq -r '.tag_name')
          echo "version=$version" >> $GITHUB_OUTPUT

  use:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - name: Step 2 - Print Terraform version
        run: echo "🚀 Latest Terraform version is ${{ needs.fetch.outputs.tf_version }}"

          
          
